language: C

os:
  - linux
  - osx

env:
    matrix:
        - NUMPY_VERSION=1.12 PYTHON_VERSION=2.7
        - NUMPY_VERSION=1.15 PYTHON_VERSION=3.6


before_install:
    - if [ $TRAVIS_OS_NAME == "linux" ]; then wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
    - if [ $TRAVIS_OS_NAME == "osx" ]; then wget http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh; fi
    - bash ./miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - conda update --yes conda

install:
    - conda create --yes -n test python=$PYTHON_VERSION
    - source activate test
    - if [ $TRAVIS_OS_NAME == "linux" ]; then conda install -y gcc_linux-64; fi
    - conda install --yes numpy=$NUMPY_VERSION nose cython mpi4py
    - conda install -c bccp nbodykit
    - python setup.py install

script:
    - python setup.py test

deploy:
    - provider: pypi
      distributions: sdist
      user: "rainwoodman"
      password:
          secure: "l2vPJwmSojLOjHOQag7lY6kZJJLaosxqGFVmmuCuxTQEoxmnNlQAOPo/yC1rlgxxc3YHnMwPHfFSbhHBPrXfKpqUBhWDV26Fc8aj/uY1+jGxvQ9UEWu78D1CxqqwS6k90d9dR4QClrBwpuOVNqpsdqoq4u0TgHd0QxywJUq/ZnhWtYEq2wSVv2w4YIlWNLBn38Yr1KmaCC9F0sbLyqUoqRQcnSGSqabvATx3cqT04EYEMmjkUo5HtIjUlOzEKt+Ek6ycQfAFrFwX5X5gRBdouBKBpMfiK0VsHwmJczmxQlgspBJehU6us4SB7XNVS5jDNPGB/kqLFjMZICFf1xzG8VVg0gEnynYDuJUaKtI96NxgQy049bK1CHkogK/UGmzcITO/0GMkzli/s1jIxN1J67cqJ5GI5oXf1hmVRKUaTz9Jhvm0jl4QqLRD3JFf03qcMA2LfOVenEM72H9+Q1CvamfYNkDqZHAJYiCCbVjBybHfi0Nsr52eqgS9W6tJ10avUyXiLWfYZHwZYgaLq0jtpqFim3UKQDXKiYvpKuOaN7POxo3hwllt3ONJEVDJNOMyG2EGTzrPrzzxi5zj0350k0QDS9X629H/XCYfX+5ohH5cPeZjVWvE/Q893bwSCqkDOTXBDpSeZDKtXN3FHDyQAw4hRrIgSsbXyX9GAlj+vPA="
      on:
        tags   : true
        condition : ${TRAVIS_JOB_NUMBER##*.} == 1
